### PR TITLE
Allow disabling dark support

### LINKED ISSUE #5: Dark support can't be disabled by setting `dark: false`
Title is enough.

Related: #4

Might get fixed by modifying: 

https://github.com/ije/html/blob/8028de5e9dc9e08aec698b806a952a93a7b7f100/mod.tsx#L114-L119

### PR DESCRIPTION
**Pull request by roj1512**
- Fixes #5

### CODE REVIEW

**Comment by vixalien** [comment]
lgtm. @ije what's your thoughts??

**Review by ije — COMMENTED** [review]
why not just remove the script when the `dark` equals `false`？

**Comment by roj1512** [comment]
So the user might try the dark mode manually?

**Comment by ije** [comment]
> So the user might try the dark mode manually by setting `color-scheme`?

right!

**Comment by vixalien** [comment]
I think it the script also needs to be disabled when you set `dark` to `true` cause you won't need the script to detect that.

**Comment by roj1512** [comment]
@vixalien I think `dark: true` is not for enforcing dark mode. It's for switching to dark mode automatically when the user's browser prefers.

**Comment by vixalien** [comment]
Well the variable name has a different meaning I believe. Then I thinks its alright.

**Comment by roj1512** [comment]
I've understood it like this:

- dark unset or true = auto switch with the media query `prefers-color-scheme`, or `window.setColorScheme`
- dark false = no auto switch with the media query `prefers-color-scheme`*. `window.setColorScheme` will still work

*Which this PR fixes.

**Comment by vixalien** [comment]
Yep. That's it

**Comment by ije** [comment]
**update**: in 0.9.0, i added `colorScheme?: "dark" | "light" | "auto"` instead of the `dark` option

**Comment by vixalien** [comment]
Yep. that's more undestandable.

**Pull request merged**
